### ISSUE TITLE
Fix formatting issues on Recipient view

### ISSUE THREAD

**Issue by daniefer** [LBBLUG/BASTAS#5]
**Acceptance Criteria:**
view will look good on a 800X600 monitor screen

**Excludes:**
smaller screens such as tables and phones

**Comment by bmcgonag** [comment]
@daniefer i've updated the HTML, but having a hard time testing.  I'll try again later, and see if I can get it to work.

**Comment by bmcgonag** [comment]
Ok, @daniefer this should be fixed properly.  It will work down to 800 x 600 resolution.  If you go too narrow (e.g. on a phone), the checkboxes are covered by the full width div of the delete button, and you can't check or uncheck them.

**Comment by daniefer** [comment]
@bmcgonag - I tested this out looks like it is working correctly. I also commented out the links we are not using yet in the nar-bar so that the nar-bar wraps at the same time as the rest of the page. If it is good with you I say we can close out this task.
