### ISSUE TITLE
Clicking Add twice and then Remove removes the first Gift in the list regardless of the button pressed

### ISSUE THREAD

**Issue by daniefer** [LBBLUG/BASTAS#6]
**Description:**
When you click delete on the recipients view for a row that has not been saved yet, there is no way for the page to know which html row to remove so it removes the first one even if there is text in it.

**Acceptance Criteria:**
Fix it so you can delete the row you clicked the delete button on.

**Comment by daniefer** [comment]
Gave each gift an index property so when the view loads each gift is given the index from the gifts array. This index is then used to removed the row on the Delete button click event. When adding a row and before saving, the row is given the same index. Index is not persisted in the DB.

**Comment by daniefer** [comment]
Fixed a typo in the updateGift stored procedure as well. This could be the cause of the what we are seeing in Issue #3.

**Comment by daniefer** [comment]
@bmcgonag - Can you review this and test this for me? I have tested it locally already, but I want to get a second opinion before closing this out.

**Comment by bmcgonag** [comment]
@daniefer  This appears to be fixed and working properly.
